# Development Dockerfile
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install

# Copy project files
COPY . .

# Expose development server port
EXPOSE 3000


RUN apk update
RUN apk add git
RUN git config --global user.name "aborger"
RUN git config --global user.email "aborger@orbital-robotics.com"

# Start development server
CMD ["npm", "start"]